server:
  port: 0 # random port
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/msa-user
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # Eureka server에 등록
    fetch-registry: true # registry에 있는정보 가져오기
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # Eureka Server url

greeting:
  message: Welcome !!

logging:
  level:
    com.example.userservice: DEBUG

token:
  expiration_time: 86400000
  secret: R8n9rpDN1Q6LJgD2LIC0uqAZEFCiPKeBudPTU10cDPU=