server:
  port: 0 # random port ??
spring:
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true # Eureka server? ??
    fetch-registry: true # Eureka Server? ?? ?????? ??? ????? ??????? ???? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # Eureka Server url ??