server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    discovery:
      enabled: false
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter Base Message
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
            #            - AddRequestHeader=first-request, first-request-header2
            #            - AddRequestHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
            #            - AddRequestHeader=second-request, second-request-header2
            #            - AddRequestHeader=second-response, second-response-header2
            - name: CustomFilter
            - name: LoggingFilter # 파라미터가 있으면 name 이 있어야한다.
              args:
                baseMessage: Logging Filter BaseMessage
                preLogger: true
                postLogger: false